# Generated by Django 2.1.15 on 2020-10-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0002_auto_20201027_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='describe',
        ),
    ]
