# Generated by Django 2.1.15 on 2020-10-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0003_remove_artwork_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='time'),
        ),
    ]
