# Generated by Django 2.1.15 on 2020-10-28 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0005_auto_20201028_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabulousComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='STATUS')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('fabulousComment_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabulousComment_user', to='backstage.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '点赞评论',
                'verbose_name_plural': '点赞评论',
                'db_table': 'fabulousComment',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='fabulous_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='comment',
            name='fabulous_user',
            field=models.ManyToManyField(blank=True, related_name='fabulous_add_user', to='backstage.User', verbose_name='点赞人'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='detail'),
        ),
        migrations.AddField(
            model_name='fabulouscomment',
            name='fabulous_Comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabulous_Comment', to='backstage.Comment', verbose_name='评论'),
        ),
    ]
