# Generated by Django 2.1.15 on 2020-11-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0006_auto_20201028_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='fabulous_user',
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='code'),
        ),
    ]
