# Generated by Django 2.1.15 on 2020-11-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0007_auto_20201103_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address'},
        ),
        migrations.AlterModelOptions(
            name='artwork',
            options={'verbose_name': 'artwork', 'verbose_name_plural': 'artwork'},
        ),
        migrations.AlterModelOptions(
            name='browse',
            options={'verbose_name': 'browse', 'verbose_name_plural': 'browse'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comment'},
        ),
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name': 'commodity', 'verbose_name_plural': 'commodity'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'education', 'verbose_name_plural': 'education'},
        ),
        migrations.AlterModelOptions(
            name='fabulous',
            options={'verbose_name': 'fabulous', 'verbose_name_plural': 'fabulous'},
        ),
        migrations.AlterModelOptions(
            name='fabulouscomment',
            options={'verbose_name': 'fabulousComment', 'verbose_name_plural': 'fabulousComment'},
        ),
        migrations.AlterModelOptions(
            name='homeselected',
            options={'verbose_name': 'homeSelected', 'verbose_name_plural': 'homeSelected'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'fabulous', 'verbose_name_plural': 'fabulous'},
        ),
        migrations.AlterModelOptions(
            name='medium',
            options={'verbose_name': 'medium', 'verbose_name_plural': 'medium'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='onnowartwork',
            options={'verbose_name': 'onNowArtwork', 'verbose_name_plural': 'onNowArtwork'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'order'},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'proposal', 'verbose_name_plural': 'proposal'},
        ),
        migrations.AlterModelOptions(
            name='remind',
            options={'verbose_name': 'remind', 'verbose_name_plural': 'remind'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'shoppingCart', 'verbose_name_plural': 'shoppingCart'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address_info',
            field=models.TextField(blank=True, null=True, verbose_name='address_info'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='artist'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist_letter',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='artist_letter'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='comment_number',
            field=models.IntegerField(default=0, verbose_name='comment_number'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='fabulous_number',
            field=models.IntegerField(default=0, verbose_name='like_number'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='like_number',
            field=models.IntegerField(default=0, verbose_name='fabulous_number'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='look_number',
            field=models.IntegerField(default=0, verbose_name='look_number'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artwork_medium', to='backstage.Medium', verbose_name='medium_id'),
        ),
        migrations.AlterField(
            model_name='browse',
            name='browse_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='browse_artwork', to='backstage.Artwork', verbose_name='artist'),
        ),
        migrations.AlterField(
            model_name='browse',
            name='browse_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='browse_user', to='backstage.User', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_artwork', to='backstage.Artwork', verbose_name='artwork'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=2000, verbose_name='comment_text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='backstage.User', verbose_name='comment_user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='fabulous_num',
            field=models.IntegerField(default=0, verbose_name='fabulous_num'),
        ),
        migrations.AlterField(
            model_name='education',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='education',
            name='describe',
            field=models.CharField(max_length=1000, verbose_name='describe'),
        ),
        migrations.AlterField(
            model_name='fabulous',
            name='fabulous_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabulous_artwork', to='backstage.Artwork', verbose_name='artwork'),
        ),
        migrations.AlterField(
            model_name='fabulous',
            name='fabulous_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabulous_user', to='backstage.User', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='fabulouscomment',
            name='fabulousComment_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabulousComment_user', to='backstage.User', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='fabulouscomment',
            name='fabulous_Comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabulous_Comment', to='backstage.Comment', verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='homeselected',
            name='home_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_artwork', to='backstage.Artwork', verbose_name='artwork'),
        ),
        migrations.AlterField(
            model_name='homeselected',
            name='sequence',
            field=models.IntegerField(default=0, verbose_name='sequence'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_artwork', to='backstage.Artwork', verbose_name='artwork'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='backstage.User', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='medium_id'),
        ),
        migrations.AlterField(
            model_name='news',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='artist'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='describe',
            field=models.CharField(max_length=1000, verbose_name='describe'),
        ),
        migrations.AlterField(
            model_name='onnowartwork',
            name='on_now_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='on_now_artwork', to='backstage.Artwork', verbose_name='artwork'),
        ),
        migrations.AlterField(
            model_name='onnowartwork',
            name='sequence',
            field=models.IntegerField(default=0, verbose_name='sequence'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backstage.Address', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_money',
            field=models.FloatField(default=0, verbose_name='money'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sell_number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='backstage.User', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='remind',
            name='flag',
            field=models.IntegerField(default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='remind',
            name='remind_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remind_user', to='backstage.User', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='flag',
            field=models.IntegerField(default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='order_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sell_number'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='shoppingCart_commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoppingCart_commodity', to='backstage.Commodity', verbose_name='commodity'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='shoppingCart_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoppingCart_user', to='backstage.User', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='shopping_num',
            field=models.IntegerField(default=1, verbose_name='number'),
        ),
    ]
