# Generated by Django 2.1.15 on 2020-11-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0008_auto_20201112_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_user', to='backstage.User', verbose_name='Upload users'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_user', to='backstage.User', verbose_name='Upload users'),
        ),
    ]
